import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Welcome! - BLOGSY Community",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="min-h-screen py-8">
      <div className="flex flex-col flex-1 items-center justify-center">
        {children}
      </div>
    </section>
  );
}
