import type { Metadata } from "next";
import { NewPostHeader } from "@/features/feed/components/post/new-post-header";

export const metadata: Metadata = {
  title: "New Post-BLOGSY Community",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="overflow-y-hidden">
      <NewPostHeader />
      {children}
    </section>
  );
}
